### ISSUE TITLE
Do you want my presentation on 10 layers of container security?

### ISSUE THREAD

**Issue by alberttwong** [OWASP/community-docs#2]

**Comment by jmarcil** [comment]
Hello Albert,

no sorry!

This repo is for documents doing the promotion of OWASP to various target audiences.

Your proposal is more "actual content" so it doesn't qualify for what we're trying to achieve.

I'm not against adding presentation materials, but they would have to be about OWASP projects or content.

Thanks for your offer,

- Jonathan
